export { MAX_MATRIX_ELEMENTS, MatrixBacking, PineMatrix } from "./pine-matrix.js";
export {
  add_col,
  add_row,
  col,
  columns,
  concat,
  copy,
  elements_count,
  fill,
  get,
  newBool,
  newColor,
  newFloat,
  newInt,
  newMatrix,
  newString,
  remove_col,
  remove_row,
  reshape,
  reverse,
  row,
  rows,
  set,
  sort,
  submatrix,
  swap_columns,
  swap_rows,
  type BoolMatrix,
  type ColorMatrix,
  type FloatMatrix,
  type IntMatrix,
  type StringMatrix,
} from "./core.js";
export { avg, diff, max, median, min, mode, sum, trace } from "./stats.js";
export {
  det,
  eigenvalues,
  eigenvectors,
  inv,
  kron,
  mult,
  pinv,
  pow,
  rank,
  transpose,
} from "./linalg.js";
export {
  is_antidiagonal,
  is_antisymmetric,
  is_binary,
  is_diagonal,
  is_identity,
  is_square,
  is_stochastic,
  is_symmetric,
  is_triangular,
  is_zero,
} from "./predicates.js";
